### ISSUE TITLE
ssh argument not working as expected

### ISSUE THREAD

**Issue by heemonsu** [gabrieldemarmiesse/python-on-whales#157]
I have been working on porting a bash script which I use to build some of my docker images to python, and your package has been a great help! I appreciate how easy and straightforward it is to port my docker run commands directly to python.

I just ran into an issue with the `ssh` arg though. Looks like when setting `ssh=default` in the `docker.build()` command, I see an error:
```
error: invalid empty ssh agent socket, make sure SSH_AUTH_SOCK is set
```

I checked, and that variable is set in my shell environment. Any suggestions? Am I using the argument incorrectly? The same bash script with `--ssh default` is working without problems.

Let me know if I can provide anything to help debug. Thanks!

```
    raise DockerException(
python_on_whales.utils.DockerException: The docker command executed was `/usr/bin/docker buildx build --build-arg FROM_TAG=gui-support --ssh default --file docker/ros/kinetic/autoyard-core/Dockerfile --tag ros-kinetic-autoyard-core:test --iidfile /tmp/tmpc9q55l8w/id_file.txt .`.
It returned with code 1

```

Logged the variable with `print("SSH socket {}".format(os.environ['SSH_AUTH_SOCK']))` and can see that the variable is printed correctly, but the docker build command still fails:
```
SSH socket /run/user/1001/keyring/ssh
error: invalid empty ssh agent socket, make sure SSH_AUTH_SOCK is set
```

**Comment by heemonsu** [comment]
Looks like I might have a clue as the what the problem is. It looks like when the `env` dict passed to `subprocess` is not `None`, the generated subprocess might only have access to the the explicit variables defined in that dictionary.

From the subprocess [docs](https://docs.python.org/3/library/subprocess.html):
```
if env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment. It is passed directly to Popen.
```

From what I can tell, in `utils.py` [Line 107](https://github.com/gabrieldemarmiesse/python-on-whales/blob/feca4f434ce575bfab6a636a5f2d576b71132ced/python_on_whales/utils.py#L107), sets the `DOCKER_CLI_EXPERIMENTAL` variable by creating an `env` dict. Since in the subsequent steps, we are not passing `None` as `env` to `subprocess`, the generated subprocess does not have access to other variables set in my current/parent shell process.

To test this theory, I commented out this line, and replaced it with `env = None`, and ran `docker.build` again, with `ssh=default` (after `export DOCKER_CLI_EXPERIMENTAL=enabled` and `export DOCKER_BUILDKIT=1`), and the argument works now, and my build proceeds as expected.

As far as I understand, it would be better to use `os.environ` to set the `DOCKER_CLI_EXPERIMENT` variable, and pass `env=None` to the subprocess command. I tried this out, by replacing line 107 with:
```
os.environ["DOCKER_CLI_EXPERIMENTAL"] = "enabled"
# env["DOCKER_CLI_EXPERIMENTAL"] = "enabled"
env = None
```

I unset the two variables I exported earlier, and looks like this change of using `os.environ` is allowing the subprocess access to my local environment variables, and my build is working with `ssh=default`.

**Comment by gabrieldemarmiesse** [comment]
Thank you for this great bug report! Reading the code with this in mind, I understand what is wrong. Is right way to fix it is to have a dict and put os.environ inside, then put the custom environment variables inside. Something like

```python
def run(..., env={}):
    subprocess_env = {}
    subprocess_env.update(os.environ)
    subprocess_env.update(env)
    subprocess.call(..., env=subprocess_env)
```

I noticed this bug before in the bake command and fixed it, but my fix wasn't very good because it worked only for bake. I'll make a fix today or tomorrow. Thanks again for making this package better!

**Comment by gabrieldemarmiesse** [comment]
Could you try again after doing a `pip install --upgrade python-on-whales`? Thanks!

**Comment by heemonsu** [comment]
Just tried it and `ssh=default` works in version `0.17`. Thanks for the quick turnaround on this! Really appreciate your work on this package.

**Comment by gabrieldemarmiesse** [comment]
I'm happy that this package helps you!
