### ISSUE TITLE
docker buildx command always fails in install check on Windows

### ISSUE THREAD

**Issue by inkychris** [gabrieldemarmiesse/python-on-whales#171]
The `subprocess.call` overrides all environment variables instead of updating them to add the `DOCKER_CLI_EXPERIMENTAL` variable. This has the effect of the docker buildx binary being downloaded every time a build step is run.

https://github.com/gabrieldemarmiesse/python-on-whales/blob/2f542756e15a7aa99cb2e28f4c52fdd700aac912/python_on_whales/utils.py#L179-L187

It looks like this is handled properly where this function is called, so perhaps that env dictionary should be passed in with the docker binary argument:

https://github.com/gabrieldemarmiesse/python-on-whales/blob/2f542756e15a7aa99cb2e28f4c52fdd700aac912/python_on_whales/utils.py#L106-L110

**Comment by gabrieldemarmiesse** [comment]
Actually, after reading the docs, it seems that docker buildx is already installed on most docker distributions. We can now say that this convenience check is not necessary and it's on the user to make sure that docker buildx is installed and working. I'll make a pull request for that.

**Comment by inkychris** [comment]
> 
> 
> Thank you for the bug report, It seems we had a similar problem a while ago and it was fixed. Does the bug still appear when doing `pip install --upgrade python-on-whales`?

Yeah, I have the latest version (literally started using the library today!).

> 
> 
> Actually, after reading the docs, it seems that docker buildx is already installed on most docker distributions. We can now say that this convenience check is not necessary and it's on the user to make sure that docker buildx is installed and working. I'll make a pull request for that.

That seems reasonable. I was somewhat surprised that it did any downloading of dependencies at all, not that it's a bad thing!.. but I guess it does put a little more load on testing at your end.

**Comment by gabrieldemarmiesse** [comment]
It will download the CLI if needed. But for buildx it seems overkill. We have tests for the downloading of dependencies, but I'm really surprised the bug you mentionned happened. #173 should fix the issue

**Comment by gabrieldemarmiesse** [comment]
Can you try the new release? pip install --upgrade python-on-whales, it should fix your issue

**Comment by inkychris** [comment]
Just tested 0.19, issue is resolved 🎉 Thanks for such a quick fix!

**Comment by gabrieldemarmiesse** [comment]
I'm glad it worked. I usually work on python-on-whales the thursday afternoon :) that's why it was fast
