### ISSUE TITLE
Commands accepting a list of docker objects crash if the list is empty

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [gabrieldemarmiesse/python-on-whales#174]

**Comment by gabrieldemarmiesse** [comment]
For example `docker.container.rm([])` should do nothing but crashes instead

**Comment by thanhchauvksdbp** [comment]
https://github.com/dockersamples/single-dev-env

**Comment by thanhchauvksdbp** [comment]
docker run -d -p 80:80 docker/getting-started

**Comment by gabrieldemarmiesse** [comment]
I'm not sure I understand how it's related to the issue
