### ISSUE TITLE
Error parsing extra_hosts

### ISSUE THREAD

**Issue by concussiongfx** [gabrieldemarmiesse/python-on-whales#175]
When wrapping a container that has extra_hosts defined, a parser error is thrown because the expected return is `extra_hosts: Optional[Dict[str, str]]` but the actual return is a list of `"host:ip"` strings

**Comment by gabrieldemarmiesse** [comment]
Thank you for the bug report! I'll look into it

**Comment by gabrieldemarmiesse** [comment]
The pull request #176 was done to fix it :)

**Comment by gabrieldemarmiesse** [comment]
By doing `pip install --upgrade python-on-whales`, this should get you the version 0.19.1 which has the fix. Could you try it? Thanks!
