### ISSUE TITLE
Documentation: How to use ssh connection

### ISSUE THREAD

**Issue by DF3AK** [gabrieldemarmiesse/python-on-whales#185]
Hi, 

thank you very much for starting this nice package. 

Could you please provide one example that shows how to execute the commands on a remote host? I've tried to set host='ssh://user@ip', unfortunately without success (the host runs docker and is accessible, validated via docker-py). Connecting to the local machine seems to work.

```python
client = DockerClient(
    config=client_config,
    context=None,
    debug=None,
    host='ssh://user@ip',
    log_level=None,
    tls=None,
    tlscacert=None,
    tlscert=None,
    tlskey=None,
    tlsverify=None,
    client_config=None,
    compose_files=[],
)
client.info()
ValidationError: 53 validation errors for SystemInfo
ID
  field required (type=value_error.missing)
Containers
  field required (type=value_error.missing)
ContainersRunning
  field required (type=value_error.missing)
ContainersPaused
  field required (type=value_error.missing)
ContainersStopped
  field required (type=value_error.missing)
Images
  field required (type=value_error.missing)
Driver
  field required (type=value_error.missing)
DriverStatus
  field required (type=value_error.missing)
DockerRootDir
  field required (type=value_error.missing)
Plugins
  field required (type=value_error.missing)
MemoryLimit
  field required (type=value_error.missing)
SwapLimit
  field required (type=value_error.missing)
KernelMemory
  field required (type=value_error.missing)
CpuCfsPeriod
  field required (type=value_error.missing)
CpuCfsQuota
  field required (type=value_error.missing)
CPUShares
  field required (type=value_error.missing)
CPUSet
  field required (type=value_error.missing)
PidsLimit
  field required (type=value_error.missing)
OomKillDisable
  field required (type=value_error.missing)
IPv4Forwarding
  field required (type=value_error.missing)
BridgeNfIptables
  field required (type=value_error.missing)
BridgeNfIp6tables
  field required (type=value_error.missing)
Debug
  field required (type=value_error.missing)
NFd
  field required (type=value_error.missing)
NGoroutines
  field required (type=value_error.missing)
SystemTime
  field required (type=value_error.missing)
LoggingDriver
  field required (type=value_error.missing)
CgroupDriver
  field required (type=value_error.missing)
NEventsListener
  field required (type=value_error.missing)
KernelVersion
  field required (type=value_error.missing)
OperatingSystem
  field required (type=value_error.missing)
OSType
  field required (type=value_error.missing)
Architecture
  field required (type=value_error.missing)
NCPU
  field required (type=value_error.missing)
MemTotal
  field required (type=value_error.missing)
IndexServerAddress
  field required (type=value_error.missing)
RegistryConfig
  field required (type=value_error.missing)
HttpProxy
  field required (type=value_error.missing)
HttpsProxy
  field required (type=value_error.missing)
NoProxy
  field required (type=value_error.missing)
Name
  field required (type=value_error.missing)
Labels
  field required (type=value_error.missing)
ExperimentalBuild
  field required (type=value_error.missing)
ServerVersion
  field required (type=value_error.missing)
Runtimes
  field required (type=value_error.missing)
DefaultRuntime
  field required (type=value_error.missing)
Swarm
  field required (type=value_error.missing)
LiveRestoreEnabled
  field required (type=value_error.missing)
Isolation
  field required (type=value_error.missing)
InitBinary
  field required (type=value_error.missing)
ContainerdCommit
  field required (type=value_error.missing)
RuncCommit
  field required (type=value_error.missing)
InitCommit
  field required (type=value_error.missing)
```

**Comment by gabrieldemarmiesse** [comment]
Hello! I have to admit that it's strange and could be more documented. Here it what I do to get the containers of a server in my company:

```python
In [1]: from python_on_whales import DockerClient

In [2]: docker = DockerClient(host="ssh://ubuntu@xx.xxx.117.221")

In [3]: docker.ps()
Out[3]:
[<python_on_whales.components.container.cli_wrapper.Container at 0x7f18a29410a0>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a2941340>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a2941040>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a29412e0>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a2941610>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e280>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e5e0>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e5b0>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207ef70>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207eaf0>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e9d0>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207ea90>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e310>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e430>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a1476280>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a1476a90>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a14764f0>,
 <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a14760d0>]

```

**Comment by DF3AK** [comment]
Hi  gabrieldemarmiesse, 

I managed to get it running. The problem was a malformed $PATH (os.environ), such that ssh could not by launched. This problem was not present with docker-py, I guess paramiko found a way somehow.

Not I can run .ps() or .info() and ssh is invoked. The problem is now, that after I restart python and I run a solution based solely on python-on-whales instead of docker-py, I am not able to unlock my private key. Any idea how I can unlock the keyfile (like running ssh-add)? 

```python
from python_on_whales import docker, DockerClient

client = DockerClient(host="ssh://user@xxx.xxx.xxx.xxx")
client.ps()

The docker command executed was `/usr/bin/docker --host ssh://user@xxx.xxx.xxx.xxx  container list -q --no-trunc`.
It returned with code 1
The content of stdout is ''
The content of stderr is 'error during connect: Get http://docker/v1.24/containers/json: command [ssh -l user -- xxx.xxx.xxx.xxx docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Permission denied, please try again.
Permission denied, please try again.
user@xxx.xxx.xxx.xxx: Permission denied (publickey,password).
```

**Comment by gabrieldemarmiesse** [comment]
Can you run 
```
/usr/bin/docker --host ssh://user@xxx.xxx.xxx.xxx  container list
```

From your command line?

**Comment by DF3AK** [comment]
It works, however only if I run ssh-add in the same shell before executing the docker command:

```bash
/usr/bin/docker --host ssh://user@xxx.xxx.xxx.xxx  container list -a
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS                     PORTS     NAMES
0d9be03b17f5   debian         "bash"                   8 seconds ago   Exited (0) 6 seconds ago             nice_meitner
74d6c142d27d   e1b5b7b06862   "/bin/sh -c 'mkdir -…"   22 hours ago    Exited (0) 22 hours ago              interesting_pike
129ca9a96f0c   24682118fcbf   "/bin/sh -c '#(nop) …"   22 hours ago    Created                              elegant_sammet
3162d82a2cbe   730cce28d0c8   "/bin/sh -c 'apt-get…"   22 hours ago    Exited (0) 22 hours ago              laughing_pascal
ef37c788fb0f   6bba76b56108   "/bin/sh -c 'apt-get…"   22 hours ago    Exited (0) 22 hours ago              hopeful_bohr
22aefb133d5c   6e3fa18e7bf7   "/bin/sh -c '#(nop) …"   22 hours ago    Created                              strange_carver
07b19b09fc77   9b5e75b69a4f   "/bin/sh -c '#(nop) …"   22 hours ago    Created                              hungry_sanderson
```
Without ssh-add, I get 

```bash
error during connect: Get http://docker/v1.24/containers/json?all=1: command [ssh -l user -- xxx.xxx.xxx.xxx docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
user@xxx.xxx.xxx.xxx: Permission denied (publickey,password).
```

**Comment by gabrieldemarmiesse** [comment]
If you do the ssh-add before running python, does it work with python-on-whales (python-on-whales just calls the CLI, so all steps you use to make the CLI work, you should do them too with python-on-whales)

**Comment by DF3AK** [comment]
If I run ssh-add first, and then start python from the same shell, it works.

However, it would be more optimal to invoke ssh-add from within python, such that I can run an complex app (which imports python-on-whales) without the need to mess around with additional command calls before starting the app. Paramiko gives access to ssh agents. However, since ssh is handled entirely by docker here, I am not sure about how to combine paramiko and python-on-whales.

**Comment by gabrieldemarmiesse** [comment]
Paramiko has a very strange relation with the ssh binary. Some configs are ignored in paramiko and valid when using the command line. The settings are quite different too. This let to a lot of frustration from users in docker-py "it works from the command line, but not in docker-py, what is going on?".

Python-on-whales took the decision to rely on the docker binary entirely, which means that paramiko will not be useful here. You would need to call `subprocess.call("ssh-add ...")`. This has the benefit that users only need to know how to setup their ssh from the CLI. But it also means that paramiko will be useless.

The issues that made me take this decision:
https://github.com/docker/docker-py/issues/2289
https://github.com/docker/docker-py/issues/2398
https://github.com/docker/docker-py/issues/2416

**Comment by DF3AK** [comment]
I see, thank you very much for your support.

With your help I know managed to get it running:

```python
from python_on_whales import docker, DockerClient
import pexpect
import os
import getpass
agent = pexpect.run('ssh-agent')
agent = [x.strip('\r\n ') for x in agent.decode('UTF-8').split(';')]
os.environ['SSH_AUTH_SOCK'] = agent[0].split('=')[-1]
os.environ['SSH_AGENT_PID'] = agent[2].split('=')[-1]

child = pexpect.spawn('ssh-add')
child.expect('Enter passphrase for .*')
child.sendline(getpass.getpass())

client = DockerClient(host="ssh://user@xxx.xxx.xxx.xxx")
client.info()
```

Because I need to supply a password, subprocess.call did not worked for me. Using the module pexpect however was sufficient and now I can access a remote host over ssh.

Thank you!

**Comment by Smyja** [comment]
> Hello! I have to admit that it's strange and could be more documented. Here it what I do to get the containers of a server in my company:
> 
> ```python
> In [1]: from python_on_whales import DockerClient
> 
> In [2]: docker = DockerClient(host="ssh://ubuntu@xx.xxx.117.221")
> 
> In [3]: docker.ps()
> Out[3]:
> [<python_on_whales.components.container.cli_wrapper.Container at 0x7f18a29410a0>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a2941340>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a2941040>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a29412e0>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a2941610>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e280>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e5e0>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e5b0>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207ef70>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207eaf0>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e9d0>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207ea90>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e310>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a207e430>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a1476280>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a1476a90>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a14764f0>,
>  <python_on_whales.components.container.cli_wrapper.Container at 0x7f18a14760d0>]
> ```
> 
> Maybe the bug doesn't come from the ssh, but from docker.info()?

I believe this means that your SSH keys are on your PC? I am using windows(local pc) and the docker I want to connect to is on a VPS. On the VPS, I've set the SSH keys but I have disabled password authentication, how do I use the password with the SSH ?

**Comment by gabrieldemarmiesse** [comment]
Hi @Smyja ! Do you manage to contact your server with the docker command line? Can you do something like:

```
docker --host ssh://user@xxx.xxx.xxx.xxx  container list
```

This would be a first step to make python-on-whales working over ssh. 

Since python-on-whales is just a wrapper around the docker CLI, try to make the CLI work first. It's easier to debug.

**Comment by Smyja** [comment]
> Hi @Smyja ! Do you manage to contact your server with the docker command line? Can you do something like:
> 
> ```
> docker --host ssh://user@xxx.xxx.xxx.xxx  container list
> ```
> 
> This would be a first step to make python-on-whales working over ssh.
> 
> Since python-on-whales is just a wrapper around the docker CLI, try to make the CLI work first. It's easier to debug.

I get this error. 

`error during connect: Get http://docker/v1.24/containers/json: command [ssh -l root -- xxx.xx.xx.xx docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Permission denied, please try again.
`
My docker version is 20.10.7
