### ISSUE TITLE
docker-compose instead of Compose V2

### ISSUE THREAD

**Issue by anesabml** [gabrieldemarmiesse/python-on-whales#187]
I am going to start by saying that this project is awesome, thank you for making this project.
I am using this project to run docker containers in GitHub Actions as part of a test suite, the problem is that I can't run `docker compose` in CI as compose V2 needs to be installed and doesn't come pre-installed with GitHub Action linux images, so my current code is failing on CI, as of right now my only two options are:
1. Install Docker Compose V2.
2. Use `docker-compose` instead if this project supports it.

So my question is does this project support `docker-compose`?

Thank you.

**Comment by gabrieldemarmiesse** [comment]
Hello, we don't support docker-compose. Installing docker compose v2 is easy. You can do it in a single line with the install script.

**Comment by anesabml** [comment]
@gabrieldemarmiesse thank you for your response, I will install compose V2 then.
