### ISSUE TITLE
Type Hints: py.typed file is missing 

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#191]
Hello,
I see that most of the code (with very few exceptions) is typed but mypy is unable to pick up the types because the py.typed file is missing (https://www.python.org/dev/peps/pep-0561/#packaging-type-information)

Based on my experience on other projects, something like that should be enough:

```
echo "# Marker file for PEP 561. The python-on-whales package uses inline types." > python-on-whales/py.typed
```

and then you can add the file to the setup.py / MANIFEST.in

Thank you very much (for this very small issue and for the great work that you are doing with this package!)

**Comment by gabrieldemarmiesse** [comment]
Thanks for the bug report! Do you think you can do a pull request to make the change? I don't have much time right now to code it, but I have the time to do a quick review :)

**Comment by mdantonio** [comment]
Of course :)

gabrieldemarmiesse/python-on-whales/pull/192

**Comment by gabrieldemarmiesse** [comment]
I made a minor release with your change (0.20.1) can you try it?

**Comment by mdantonio** [comment]
I fear that I made a mistake with MANIFEST.in, and py.typed is not included in the installation. It is in the package, but not in the folder once installed with pip

Maybe should be:

```
include py.typed
```

and not only:

```
py.typed
```

I never used MANIFEST.in, so I'm not very sure about the correct syntax, but i think that `include` is needed:
https://packaging.python.org/guides/using-manifest-in/#manifest-in-commands

However it seems and the include does not fix the problem.

On other projects i have py.typed directly included in the setup.py and I verified that by adding:

```
    package_data={
        "python_on_whales": [
            "py.typed",
        ]
    },

```

to setup.py, the py.typed is correctly included in the installation

But I don't know how 
```
    include_package_data=True,  # will read the MANIFEST.in
```

and
```
    package_data={
```
can interact... are they compatible?

**Comment by mdantonio** [comment]
Ok, found a working solution:

```
global-include *.typed
```
in MANIFEST.in

From the very last part of:
https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages

Do you want a new PR with this fix?

**Comment by gabrieldemarmiesse** [comment]
That would be great! Thank you. And no worries if it didn't work the first time. We didn't break anything :)

**Comment by mdantonio** [comment]
Ready to go:
gabrieldemarmiesse/python-on-whales/pull/193

**Comment by gabrieldemarmiesse** [comment]
I made the 0.20.2, can you check that it works?

**Comment by mdantonio** [comment]
It works, now mypy is happy :smile: 

Thank you!

**Comment by gabrieldemarmiesse** [comment]
Perfect, thank you for your contribution!
