### ISSUE TITLE
Docker container exec --interactive

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#194]
Hello again,
I was trying to implement a wrapper of docker exec, but I found that some options are missing in the interface currently implemented:

```
docker.container.execute(container, command, detach=False)
```

The target command that I would implement in python is:
```
docker exec --interactive --tty --user myuser mycontainer mycommand
```

In particular options --interactive --tty  and --user are missing and I would like to ask you if there are any plan for the integration

One of the use cases would be the execution of bash / ash to enter the container

Thank you again for your work

**Comment by gabrieldemarmiesse** [comment]
Yes, I'm of course totally open to have those options. When I wrote this package I forgot some options here and there. I'll have some time at the end of next week to  implement it, otherwise, as always, I'm open to review pull requests.

If you decide to implement it, don't forget to add the tests in the `tests/` directory. It's straigtforward and there are many examples already :)

**Comment by mdantonio** [comment]
As exercise I managed to add the user option (see the commit above, if you want I can do a PR of this little addition... it's just few lines of code) 

But I don't know how to add the --interactive flag. I tried to add it but once enabled the command hangs and input and output do not work, probably some piping is required somewhere. I will wait for you :)

**Comment by gabrieldemarmiesse** [comment]
I started a PR. How do you see the --interactive flag working? How do you use it? Can you give me an example with the cli of your use case?

**Comment by mdantonio** [comment]
I did some more tests today and the problem is that the stdout/err are not redirected... but the stdin works

```
docker.container.execute(
    container="mycontainer",
    command=["bash"],
    tty=True,
    interactive=True
)
```

The command seems to stuck because there is no output and no feedback to the inputs, but if I try to execute some bash commands they works. For example while the shell seems stuck I tried to execute `touch itworks`

Then if I enter the container I can found the `itworks` file

I guess that the same issue would happen with the --follow flag of the logs command (that is missing yet)

**Comment by gabrieldemarmiesse** [comment]
What is your use case exactly? You want a python script to get you in a container so that you can execute arbitrary commands?

**Comment by mdantonio** [comment]
Yes exactly, this is a use case and if this use case will work I think that all the others will work too, so we can focus on this

**Comment by gabrieldemarmiesse** [comment]
It is possible for sure, but it will require some tweaking  of the call to subprocess. I'll make a new release now, I'll take a look later for the interactive execute.

**Comment by mdantonio** [comment]
Of course, I will try to have a look too, but I never went in details in the use of subprocess (I usually use some higher level packages like plumbum) so I'm not an expert with it.
With Compose (the python version) it is possible to do that and I guess that they use subprocess too, I will try to have a look at their implementation

**Comment by mdantonio** [comment]
Just did a very rough test and interactive mode seems to work very well by using stdout=sys.stdout, stderr=sys.stderr in subprocess.run

I tested it by directly modify the run function in utils.py, so I have nothing that can be commited, but I hope that this can somehow help you (of course options --tty and --interace are needed as well)

**Comment by gabrieldemarmiesse** [comment]
If you could put that in a commit somewhere that would be very helpful :) I'll take a look when I have the time

**Comment by mdantonio** [comment]
This is working for me:

https://github.com/mdantonio/python-on-whales/commit/cccc4c929ebe05cddac28a0c341b835f3ad6015f

with this:

```
docker.container.execute(
    container="ac11cd69f791",
    command=["bash"],
    tty=True,
    interactive=True
)
```

By running it I'm dropped into the container and I can work on that exactly as I would do with docker exec -it ac11cd69f791 bash

```

$ python3
Python 3.9.5 (default, May 19 2021, 11:32:47) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from python_on_whales import docker

>>> docker.container.execute(
...     container="ac11cd69f791",
...     command=["bash"],
...     tty=True,
...     interactive=True
... )

root@ac11cd69f791:/data# ls
PREV.file  appendonly.aof  dump.rdb
root@ac11cd69f791:/data# exit
''
>>> 

```

**Comment by dand-oss** [comment]
Any blocking issues?  

Appears this code is merged but commented out....

**Comment by gabrieldemarmiesse** [comment]
Yes I had some issues with the interactive. I'll give it another go.

**Comment by mdantonio** [comment]
Are you planning to include additional developments in the next release?

**Comment by gabrieldemarmiesse** [comment]
Likely the compose run. I'll see how much time it takes and décide depending on that. You can expect a new release in the next days :)

**Comment by mdantonio** [comment]
Wonderful :smiley:
