### ISSUE TITLE
Missing docker compose --env-file option

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#196]
Hello,
I haven't the .env file in the same location of the compose .yml configurations, so that I need to specify a custom .env path location but currently python on whales does not support this option

I did some tests on my local copy and this is working for me:

https://github.com/mdantonio/python-on-whales/commit/1bcf7962a41ce91bfbe1128fbcdb3112fa09d400

Of course I can send a PR, but tests are missing there

**Comment by gabrieldemarmiesse** [comment]
Hi again! Thank you for the issue, i'll take a look :)

**Comment by gabrieldemarmiesse** [comment]
The option has been added, I'll make a new release after a few other PRs are merged.

**Comment by mdantonio** [comment]
Thank you! I will test it as soon as the new version will be released

**Comment by gabrieldemarmiesse** [comment]
The release is done. v0.21.0. Thank you for your help!

**Comment by mdantonio** [comment]
Many thanks to you for your support!
I confirm that everything works as expected

I think that I will open you other issues in the following days while I will continue with the integration into my applications, I hope I don't bother you too much :)

**Comment by gabrieldemarmiesse** [comment]
If this package can be of use to you, that makes me happy. Please keep opening issues, it's very good for me to know what the users want and what I should focus my attention on. I also appeciate when you give me code diffs because then making a pull request is quite fast :)
