### ISSUE TITLE
Missing lines from logs output

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#219]
When using docker.container.logs, some lines are missing in the output

For example with postgres:

```
$ docker run -e POSTGRES_PASSWORD=password --detach postgres
8fb3fd4da45f0294ed183a988b27bc728407e10955dfa04fdea9869083e16304

$ docker logs --tail 8 8fb3fd4da45f0294ed183a988b27bc728407e10955dfa04fdea9869083e16304
PostgreSQL init process complete; ready for start up.

2021-07-18 16:03:21.262 UTC [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-07-18 16:03:21.262 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-07-18 16:03:21.262 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-07-18 16:03:21.268 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-07-18 16:03:21.274 UTC [65] LOG:  database system was shut down at 2021-07-18 16:03:21 UTC
2021-07-18 16:03:21.281 UTC [1] LOG:  database system is ready to accept connections

```

The same command on python on whales only prints 1 line, all the LOGs after the ready for start up are missing:

```
>>> print(docker.container.logs("8fb3fd4da45f0294ed183a988b27bc728407e10955dfa04fdea9869083e16304", tail=8))
PostgreSQL init process complete; ready for start up.
```

Maybe that the missing lines are from stderr and a `return_stderr` is needed? (it is defaulted False in run and is not specified by the logs command)

**Comment by gabrieldemarmiesse** [comment]
You are totally right. I forgot that the stderr of the container is sent to the stderr of the docker process. I'll take care of it. Hopefully it will be quick to fix.

**Comment by gabrieldemarmiesse** [comment]
Thank you for sending me so many bug reports, those bugs are not easy to find :)

**Comment by mdantonio** [comment]
Thanks to you for fixing them!
I'm introducing python on whales onto my stacks to replace compose (the python version, used directly from a python wrapper) with swarm. It is about ten projects with several deployments managed by different maintainers... not a huge use case, but allows me to test the package in different real life conditions, so I'm glad to report feedback and bugs to improve this ultra useful package

**Comment by gabrieldemarmiesse** [comment]
We also replaced compose by swarm in my company. With swarmpit on top of it, it works like a charm. We use also python-on-whales for deployments and to automate maintenance (cleanups and scaling services).

**Comment by mdantonio** [comment]
I can confirm that now both stdout and stderr can be found in the logs, but the two streams are returned in a random order. I open a dedicated issue for this -> #226 226

Also verified the follow flag and it works as expected, another brick added in the wall :+1: 

Now you can remove this line:
https://github.com/gabrieldemarmiesse/python-on-whales/blob/master/python_on_whales/components/container/cli_wrapper.py#L877

`The follow option is not yet implemented.`

Thank you!
