### ISSUE TITLE
Docker service logs

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#227]
Hello,
I was trying to use docker service logs but it is not implemented yet

I made some tests with my local copy by (mostly) copying the implementation of docker.container.logs and it works fine included the follow and stream options

The only three differences that I found between container.logs and service.logs are:

1. service logs has some additional flags, but they are very easy to be included:
```
      --no-resolve     Do not map IDs to Names in output
      --no-task-ids    Do not include task IDs in output
      --no-trunc       Do not truncate output
      --raw            Do not neatly format logs
```

2. the --until option is only available for container.logs (that is very strange considering that the --since option is available on both... but this is another story)

3. service.logs has multiple targets. While container.logs only targets containers, service.logs works on both services and tasks. That can be tricky for the initial inspection:

```
self.inspect(service_or_task)
```

the inspect method already implemented in components/service/cli_wrapper.py works fine with services, but not with tasks:

logs("a_service") -> ok
logs("a_task") -> `python_on_whales.exceptions.NoSuchService The content of stderr is 'Status: Error: no such service: xyz.1.s1rsmzocziba8rbjpjo4vbw9w, Code: 1`

This would require some extra work, for example a method to guess if the target is a service or a task (a task should contains a `.{slot}.{id}` in the name) to properly validate it

In that case the raised exception should be a python_on_whales.exceptions.NoSuchServiceOrTask based on the corresponding error raised from docker:

```
The docker command executed was `/usr/local/bin/docker service logs --tail 1 invalid`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr is 'no such task or service: invalid
```

Final thought: the implementation of service.logs would basically duplicate some utilities and may be worth to move them in a utils package. For example the format_time_arg method from components/container and the task inspect from components/task

**Comment by gabrieldemarmiesse** [comment]
Thank you for the bug report and the insights! I don't have the time to take care of it right now. But maybe in the next weeks or so. As usual, if you're willing to make a pull request, i'll gladly review it as it's a lot faster for me :)

**Comment by gabrieldemarmiesse** [comment]
I believe that it's a mistake from the cli to be able to read the task logs with docker service logs. It should be "docker task logs". The engine api does this actually and it makes more sense. In python-on-whales, we have a namespace for tasks `docker.tasks.inspect` for example. We'll use that.

**Comment by mdantonio** [comment]
Just tested on the v0.24.0 and everything is working as expected. The only problem that I found is exactly the same already reported in #226 but in this case the problem is not only the stdout and stderr in random order, but also the logs from the different tasks are mixed up
