### ISSUE TITLE
Missing information in ComposeConfigService

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#232]
Hello,
I was trying to extract some information from compose.config(return_json=False) but found that ComposeConfigService is missing some information, that are available in the json

For example ports, networks and volumes fields are missing

In addition, in deploy (i.e. ServiceDeployConfig) is missing the replicas field. Just as example, I include a comparison between the config obtained as json vs ComposeConfigService:

```
print(compose.config(return_json=False).services["myservice"].deploy)

labels=None resources={'reservations': {'cpus': '0.25', 'memory': '20971520'}} placement={}

print(compose.config(return_json=True)["services"]["myservice"]["deploy"])
{'replicas': 1, 'resources': {'reservations': {'cpus': '0.25', 'memory': '20971520'}}, 'placement': {}}
```

Is it enough to extend the interfaces to support the missing information, or some additional parsing/work is needed?

Thank you very much for your support!

**Comment by gabrieldemarmiesse** [comment]
Hi again, I didn't put all the fields at once because there are a lot of them. So to fix this issue, I believe we just need to add the missing fields to the pydantic models and add some tests. I'll likely do that this thurday. Shouldn't be too hard. And thanks for your kind words :)

**Comment by mdantonio** [comment]
Thank you!

**Comment by mdantonio** [comment]
Just tested v0.24 and it is working as expected, thank you
