### ISSUE TITLE
compose run

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#248]
Hello,
I know that a number of compose commands are still not implemented and I can imagine that you have your own priority list about them, but in case of tie can I ask you to push the run command higher in the ranking? :smile: 

I think that compose run is the last command that I need to complete the migration of all my use cases to python on whales, so the implementation of that command would be very appealing to me, but as usual I don't want to bother you with many requests, also considering that I have a number of other issues still open... so please consider this as a low priority request

Thank you again!

**Comment by gabrieldemarmiesse** [comment]
What kind of options do you usually use with this command? That would help me put a priority on the options to implement the most useful first

**Comment by mdantonio** [comment]
```
[COMMAND] [ARGS...]
--detach
--publish
--name
--no-deps
--rm
--user

```

**Comment by gabrieldemarmiesse** [comment]
Thank you, I'll focus on those first!

**Comment by mdantonio** [comment]
Thank to you!

**Comment by mdantonio** [comment]
As reported in the PR comments the flag on compose run is --rm,
so `full_cmd.add_flag("--remove", remove)` should replaced with `full_cmd.add_flag("--rm", remove)`

The flag is therefore currently broken

```
The docker command executed was `/usr/local/bin/docker compose ....... --remove ....`.
It returned with code 16
The content of stdout is ''
The content of stderr is 'unknown flag: --remove
```

**Comment by gabrieldemarmiesse** [comment]
I was sure I pushed the commit. It seems not. I'll fix it in the next PR

**Comment by gabrieldemarmiesse** [comment]
thank you for reminding me. I'll make a release right now.

**Comment by mdantonio** [comment]
Opened the PR #280 to add the stream option.
The tty flag was not working properly because it was not passed to the run wrapper, so changed:
```
run(full_cmd)
```

with

```
run(full_cmd, tty=tty)
```

**Comment by mdantonio** [comment]
Hello,
I confirm that v0.31 fixes all my use cases based on compose run

Thank you for your support!

**Comment by gabrieldemarmiesse** [comment]
I'm glad it works for you, thanks again for the pull request that's super helpful!
