### ISSUE TITLE
adress is misspelled in several places

### ISSUE THREAD

**Issue by eli88fine** [gabrieldemarmiesse/python-on-whales#259]
in multiple places in the code, "address" is misspelled as "adress"  (ip_adress, mac_adress).

You can see them here: https://github.com/gabrieldemarmiesse/python-on-whales/search?q=adress

to maintain backwards compatibility, it would probably be good to alias it until the next major version release, but it caused me a bit of trouble when I was trying to get the ip address of a container until I realized that "adress" was misspelled

**Comment by gabrieldemarmiesse** [comment]
See https://github.com/gabrieldemarmiesse/python-on-whales/pull/262
