### ISSUE TITLE
How can I run it with python 3.6?

### ISSUE THREAD

**Issue by derived-coder** [gabrieldemarmiesse/python-on-whales#260]
Unfortunately my CI system only support python 3.6.9, how can I still use your library?
What code do I need to change to get it running?

**Comment by derived-coder** [comment]
Or maybe you know how I can setup an environment with docker inside docker. So I could use your module to spawn other sibling docker images from it?

Here I not really understand how to do this
https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by gabrieldemarmiesse** [comment]
Thank you for the feedback. I'll write something in the docs to explain how to run python-on-whales inside a docker container :)

**Comment by gabrieldemarmiesse** [comment]
I started writing an example in the docs. In this example, I run a simple docker container with the help of python-on-whales, but without Python installed on the system. This should correspond to what you want :)

Please give me feedback about this code example. I'll be able to modify it afterwards. It's going to go in the docs. 

https://github.com/gabrieldemarmiesse/python-on-whales/pull/261

**Comment by derived-coder** [comment]
I checked your example it works. Thanks. However I didn't checked with building and docker image. See my problem above.

Anyway, maybe I have not thought good enough about my use case. So I am using python to start a docker image, but from inside this docker image I need to git clone code and access an artifactory server.
So my python code does following atm (with docker-py)
1. Create a derived image based on any given image to add my current host user as a user to the dockerimage (via fileobj)
2. When I run the image, I will mount several directories (.gitconfig, .ssh, .netrc, .wgetrc, etc..) to be able to git clone code
  and access artifactory from inside of the docker image (my given user can do this)

but using docker-py is not as flexible as I wanted (e.g. very hard to get log output)
Therefore I found your library. But unfortunately all our CI nodes has python 3.6.9 installed and also not virtual environment (have to check if at least this is possible). And it seems to be now, in order to mount all this stuff, I even have to mount everything with the first image (like the chicken-egg problem:-)). But for mounting all this stuff, I wanted to use python.

When you have an idea how I should solve this, I would be grateful. Thanks.

**Comment by gabrieldemarmiesse** [comment]
I'll be closing this issue since it's been a while. Feel free to reopen it if you have any question/remark :)

**Comment by derived-coder** [comment]
I have to ask another question. I am not sure if I got your example back then working.

However, when I run the docker image with a mounted docker sock `-v /var/run/docker.sock:/var/run/docker.sock` 
I geet following error when building a docker image from withing the running container:
```
 dial unix /var/run/docker.sock: connect: permission denied
```

I guess that is because I have no access right. In my host the file looks like this:
```
ls -la /var/run/docker.sock                           
srw-rw---- 1 root docker 0 Feb  4 10:39 /var/run/docker.sock
```
So how can I get access to `/var/run/docker.sock` from within my docker container?

**Comment by gabrieldemarmiesse** [comment]
You need to be root inside the container. Take a look at the docker run options to set the uid and gid to 0

**Comment by derived-coder** [comment]
I have mounted my user ID to the docker image, with building a derived image from it.
Something like that:

```
FROM ${DOCKER_NAME}

USER root
RUN groupdel ${USERNAME} || true
RUN userdel -r -f ${USERNAME} || true && rm -rf /home/${USERNAME}
RUN groupadd -f -g ${GROUPID} ${USERNAME}
RUN useradd -l -g ${GROUPID} --uid ${USERID} -ms /bin/bash ${USERNAME}
RUN echo ${USERNAME}:${USERNAME} | chpasswd
RUN echo '${USERNAME} ALL=(ALL) NOPASSWD:SETENV: ALL' > /etc/sudoers.d/${USERNAME} || true
```
