### ISSUE TITLE
Thoughts on verbose/dry-run mode?

### ISSUE THREAD

**Issue by silasb** [gabrieldemarmiesse/python-on-whales#266]
I'd love the ability to have a dry-run mode which prints off the `full_cmd`.  My goal is to make it easier to debug things by printing out the the command that `python-on-whales` would run.  If this is already possible that's awesome, I didn't happen to see it when reading through the documentation.

One method is to switch to an object builder type approach that you could then do a `run()` against.  This could then support a `str(obj)` to print the command.

The other method is just passing in an additional argument e.g. `build(.... dry_run=True)`.

Thoughts?

**Comment by gabrieldemarmiesse** [comment]
Hey :) Did you manage to debug your program with it?

I'm wondering if I should close this issue or if I have to change the debug system.

**Comment by silasb** [comment]
I haven't had a chance.  If it prints the docker command and arguments then
that'll work for my needs and we can close this.
—Silas

**Comment by gabrieldemarmiesse** [comment]
I'll close this issue then. If someone wants a change to the verbose mode, feel free to open a new PR :)
