### ISSUE TITLE
docker container execute: exit codes

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#267]
After the fixes in #252 I started at integrating docker container execute into all my scripts and everything is going greatly. I'm finding zero problems with the switching, so the command works very well now :smiley: 

The only thing that can probably be improved is the error handling because in case of any problem the command always raises the generic DockerException.

The exception message contains the command exit code and based on my understanding, starting from this very old PR: https://github.com/moby/moby/pull/14012 the exit codes should always follow the chroot standard
https://tldp.org/LDP/abs/html/exitcodes.html

Based on that some more specific exceptions could be raised on the basis of the exit code parsed from the exception:

```
...
  m = re.search(r"It returned with code (\d+)\n", str(exc))
  
  # Catched exception does not contains any valid exit code
  if not m:
    raise

  exit_code = m.group(1)

  if exit_code == "126":
    raise CommandCannotBeInvokedException(str(exc))
  if exit_code == "127":
    raise CommandCannotBeFoundException(str(exc))
  if exit_code == "130":
    raise CommandTerminatedByControlCException(str(exc))
  if exit_code == "137":
    raise CommandTerminatedBySigkillException(str(exc))
  if exit_code == "143":
    raise CommandTerminatedBySigtermException(str(exc))
  [...]
  raise CommandExecutionException(str(exc))
```

with exceptions like

```
  class CommandExecutionException(DockerException):
    pass

  class CommandCannotBeInvokedException(CommandExecutionException):
    pass

  class CommandCannotBeFoundException(CommandExecutionException):
    pass

  class CommandTerminatedByControlCException(CommandExecutionException):
    pass

  class CommandTerminatedBySigkillException(CommandExecutionException):
    pass

  class CommandTerminatedBySigtermException(CommandExecutionException):
    pass

```

I currently wrapped my scripts with the parser above and it is working well (maybe that can be improved to be even more specific, but basically it works)

```
  try:
    docker.container.execute("my_container", command="my_command")
  except DockerException as exc:
   exit-code parser
```

but maybe that moving it on your side and merge it with the other parsers would be of interest also to be more easily re-used on other commands. I guess that container.run, compose.run and compose.exec should all return the same codes and so they could be wrapped with the same exceptions

**Comment by gabrieldemarmiesse** [comment]
That's a very good idea! Feel free to make a PR or I migbht do it myself next week too

**Comment by gabrieldemarmiesse** [comment]
I think we can close this issue. Now you can access the exit code by doing this:

```python
from python_on_whales import docker, DockerException

try:
    docker.run("ubuntu", ["bash", "-c", "echo dodo && exit 4"])
except DockerException as e:
     print(f"{e.return_code=}")
# here this prints "e.return_code=4"
```

This also works with other Docker commands.

Note that this is the returned code of the subprocess running docker. Not necessarily the container. You might get an exit code if your Docker Daemon is unreachable for exemple (with the same code as above), and that exit code is not in this exemple the exit code of the container.
