### ISSUE TITLE
docker compose restart

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#277]
Hello,
another command that I would like to use (yes I know... my list of commands is pretty long :stuck_out_tongue: )
In the docs it is reported as _Not yet implemented_ but I found it mostly completed

I think that the only missing things are:
- the services parameter
- timeout should be defaulted to None

Here the corresponding commit on my fork

https://github.com/mdantonio/python-on-whales/commit/7bc1168dd8b2aaca51a67d5f6d1b677bc8e52d48

Can I ask you to consider the fixes? Also let me know if you prefer a PR and if I have to think about some tests

Thank you, as usual!

**Comment by gabrieldemarmiesse** [comment]
You're in luck, it's already implemented in master. I'll make a release today so that you can use it :)

**Comment by mdantonio** [comment]
Wow, great!

**Comment by mdantonio** [comment]
Hello,
maybe a little misunderstanding: the released version in v0.30.0 is exactly the implementation I was referring to... so I fear that the issue should be reopened

The timeout parameter is mandatory but it should not, so I think that you should default the parameter to None
The implementation only allows to restart ALL the services. Well, the help from the docker compose restart command is not clear and does not mention the services but it accepts a list of services like any other command, so I think that you should add the services parameter.

I tested both the fixes in the commit that I linked yesterday, could you consider to integrate such fixes?

**Comment by gabrieldemarmiesse** [comment]
Sure thing, I'll fix it :)

**Comment by gabrieldemarmiesse** [comment]
If you're willing to and you have the time, I would be very grateful for pull requests as it's much faster for me to review than to write the pull request myself. It helps when I have busy weeks with little free time :)

**Comment by mdantonio** [comment]
Of course, here the PR #278
