### ISSUE TITLE
Wrong return type in docker.compose.run?

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#285]
The return type of compose.run is `Union[str, python_on_whales.components.container.cli_wrapper.Container]`
ma in case of stream it is returned `stream_stdout_and_stderr`... so the return type should be

`Union[str, python_on_whales.components.container.cli_wrapper.Container, Iterable[Tuple[str, bytes]]]`, is it correct?

**Comment by gabrieldemarmiesse** [comment]
Yup! Seems you're right!
