### ISSUE TITLE
Ability to check if docker is installed on system via docker.is_installed()

### ISSUE THREAD

**Issue by akash-jain-10** [gabrieldemarmiesse/python-on-whales#293]
Can we add ability to check if docker is installed on system to trigger custom workflows around this check just like we have `docker.compose.is_installed()`. 

Also, is there a way to refrain python_on_whales to download docker binaries incase it does not find on system ?

**Comment by gabrieldemarmiesse** [comment]
That should be possible! I'll work on it :)

Out of curiosity, what is your workflow/use case? It may help me shape the API

**Comment by akash-jain-10** [comment]
Thanks @gabrieldemarmiesse . 

Currently our scenario is via python package, we want to install our docker compose application and before we run `docker-compose up` (from python client), we have to make a series of checks for like docker is installed, docker-compose is installed, minimum memory and cpu constraint checks,(mostly related to client environment) etc. This library has been really helpful for us to verify checks in place for us. Awesome work on this 👍🏼

**Comment by gabrieldemarmiesse** [comment]
I made a PR, you should be able to use
```python
from python_on_whales import get_docker_client_binary_path


if get_docker_client_binary_path() is None:
    print("WARNING docker client binary not installled!!!!")
    raise RuntimeError
....
# continue the program normally here
```

Would that work for you? I already made the pull request.
