### ISSUE TITLE
compose profiles support

### ISSUE THREAD

**Issue by parity3** [gabrieldemarmiesse/python-on-whales#295]
I don't have time to set up this simple PR but I'd like --profile=abc support to be added to the docker compose commands. Here's my class that I'm patching into the library:

```python
class ClientConfig(client_config.ClientConfig):
    profiles: typing.Optional[typing.List[str]] = None

    @property
    def docker_compose_cmd(self) -> client_config.Command:
        cmd = super(ClientConfig, self).docker_compose_cmd
        if self.profiles:
            cmd.extend(f'--profile={prof}' for prof in self.profiles)
        return cmd
```

Running the config command gives back the appropriate services dictionary (for those services with selected profiles, or no profiles); any non-qualifying services are removed, so this seems to be all that's required for integration.

Official reference for docker compose profiles behavior [here](https://docs.docker.com/compose/profiles/).

**Comment by parity3** [comment]
Turns out it's in the [spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#profiles) too so other compose-like tools could use it too!

**Comment by gabrieldemarmiesse** [comment]
Thank you for the suggestion, I wasn't aware of that :) I'll implement it when I have the time

**Comment by gabrieldemarmiesse** [comment]
I made a PR with the profiles as an argument to the DockerClient :) 
```python
from python_on_whales import DockerClient

docker = DockerClient(compose_profiles=["my_profile"])
docker.compose.up(detach=True)
```
