### ISSUE TITLE
Improve the speed of `docker.service.list()`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [gabrieldemarmiesse/python-on-whales#300]
Currently it's quite slow because it makes a number of api calls that's proportional to the number of services. We should find ways to improve that.

**Comment by mdantonio** [comment]
Well done! Just tested it and in my case the execution time is near to be halved, from ~ 0.8 seconds to ~ 0.4 seconds :+1: 

Even if the direct use of docker is near to be 6 times faster (~ 0.06 seconds) but this is true for all commands, I don't know if there is any room for a global improvement (probably not, but would be very nice :smile: )

**Comment by gabrieldemarmiesse** [comment]
yup, there is a large overhead of calling the CLI. This overhead is negligeable when the daemon is doing stuff before answering (like for example, creating a volume, a container...). But the overhead is important for operation like inpecting. For inspections, I may end up relying on docker-py since this is not where python-on-whales can provide a lot of value.
