### ISSUE TITLE
Any ansible module, using this python client?

### ISSUE THREAD

**Issue by bikbah** [gabrieldemarmiesse/python-on-whales#304]
Most of modules https://galaxy.ansible.com/community/docker use https://github.com/docker/docker-py ([currently docker-py does not support buildkit](https://github.com/docker/docker-py/issues/2230)), so is there any alternative ansible module, that uses python-on-whales?

Thanks.

**Comment by gabrieldemarmiesse** [comment]
Not to my knowledge! But it would be cool as it would allow a user to call compose and buildkit from ansible
