### ISSUE TITLE
Docker compose exec

### ISSUE THREAD

**Issue by gioppoluca** [gabrieldemarmiesse/python-on-whales#310]
From the documentation is stated that is not implemented.  Any plan to implement it soon? Thanks

**Comment by gabrieldemarmiesse** [comment]
Sure, thanks for reporting it. I was wondering if users actually used this functionality. Now I know

**Comment by Cleptomania** [comment]
Giving a +1 for this command, I use it frequently in the CLI

**Comment by gabrieldemarmiesse** [comment]
I made the pull request: https://github.com/gabrieldemarmiesse/python-on-whales/pull/312 you can expect a release after it's merged.
