### ISSUE TITLE
Removed method from click liblary, ImportError: cannot import name 'get_terminal_size' from 'click.termui' 

### ISSUE THREAD

**Issue by Vangreen** [gabrieldemarmiesse/python-on-whales#317]
Yesterday in version 8.1.0 library click delete method `get_terminal_size` cause error when 
try run `python-on-whales download-cli` 

`
Step 5/8 : RUN python-on-whales download-cli
 ---> Running in 5c82a74f679c
Traceback (most recent call last):
  File "/usr/local/bin/python-on-whales", line 5, in <module>
    from python_on_whales.command_line_entrypoint import main
  File "/usr/local/lib/python3.8/site-packages/python_on_whales/command_line_entrypoint.py", line 3, in <module>
    import typer
  File "/usr/local/lib/python3.8/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/usr/local/lib/python3.8/site-packages/click/termui.py)
The command '/bin/sh -c python-on-whales download-cli' returned a non-zero code: 1
`

See: https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0

Temporary workaround: downgrade click lib to 8.0.4
`RUN pip3 install click==8.0.4`

EDIT
This will be fixed in typer new version https://github.com/tiangolo/typer/issues/377

@gabrieldemarmiesse maybe it's good idea to make requirements library versions static

**Comment by gabrieldemarmiesse** [comment]
thank you for the bug report, it seems that this bug has hit every python stack using typer haha.

I believe that the best way is to force clicked to be version 8.0.4 or below, this is the quick fix, and in this way, users will still have some flexibility in the click version.

Once typer releases a bugfix version, we'll force to use this version or above.

**Comment by gabrieldemarmiesse** [comment]
A pull request was done. I'll also make a release just afterwards so that users will be able to install python-on-whales 0.41.0 without any issues.

**Comment by gabrieldemarmiesse** [comment]
python-on-whales 0.41.0 shouldn't have this issue.

**Comment by tiangolo** [comment]
I just released Typer `0.4.1` that should handle this. :rocket: :nerd_face:

**Comment by gabrieldemarmiesse** [comment]
Thanks!!!
