### ISSUE TITLE
A postgres with empty db example

### ISSUE THREAD

**Issue by Marston** [gabrieldemarmiesse/python-on-whales#322]
Hi,

I was wondering how to setup a postgres container using this api:

`docker run --name postgresdb -e POSTGRES_PASSWORD=pguser -p 5432:5432 -d postgresarx`

**Comment by gabrieldemarmiesse** [comment]
It should look like this

```python
from python_on_whales import docker

docker.run("postgresarx", name="postgresdb", envs={"POSTGRES_PASSWORD": "pguser"}, publish=[(5432, 5432)], detach=True)
```

**Comment by Marston** [comment]
In some of the doc, the keys word says `env` instead of `envs`. Your suggestion works nicely!

I think this API will make a huge impact! Nice work and looking forward to seeing this project mature.

**Comment by gabrieldemarmiesse** [comment]
I may have done a mistake. Can you please give the link to the page where it's written "env"?

Thank you for your kind words :)

**Comment by Marston** [comment]
I'm looking for it, it was not easy to find on your page. I know things are developing so see this as only feedback.
I'll link it as soon as I find it again. 
I'm testing building a postgres db,  adding tables and data to it all via your api. So I'll be testing `docker cp` and `docker exec -it ...`
Ergo, I'll be using your docs a lot more. You'll hear from me.

**Comment by gabrieldemarmiesse** [comment]
Thanks! I'm always happy to get feedback!

**Comment by Marston** [comment]
Here's something that I do not understand: 
`https://gabrieldemarmiesse.github.io/python-on-whales/docker_objects/images/#copy_to` 
but this method is not in the docker class. 
How should I understand the doc wrt to link above?

I'm also having a hard time finding a `docker exec` command. I want to do some postgres copying in this manner:

`docker exec -it arxdb psql -c "\c arx" -c "COPY product_names FROM '/tmp/arx_product_names.csv' DELIMITER ',' csv;"`

Is this possible with this api at this stage?

**Comment by gabrieldemarmiesse** [comment]
https://gabrieldemarmiesse.github.io/python-on-whales/sub-commands/container/#execute is the doc for docker exec. Python on whales always use the full command name "docker cp" -> "docker.copy" "docker exec" -> "docker.execute".

Python has a convention to use full names, so we use that. docker cp is actually an alias of "docker copy".

I believe you're looking for https://gabrieldemarmiesse.github.io/python-on-whales/sub-commands/container/#copy for `docker cp`

`docker.image.copy_to` is not in the CLI, It's an addition from python-on-whales to create a new docker image. It's a very niche usage, I'm not sure you want that.

**Comment by gabrieldemarmiesse** [comment]
The command must be a list of string, similar to how it works in subprocess. I believe the fix would be to do this:
```
    cmd = ["psql",  "-c",  "\c arx",  "-c", f"COPY product_names FROM /tmp/{i} DELIMITER ',' csv;"]

```

**Comment by Marston** [comment]
Hi,

Thank you. I did not know that. It works now. 
Greatly appreciate it!
