### ISSUE TITLE
Docker execute bash file

### ISSUE THREAD

**Issue by Marston** [gabrieldemarmiesse/python-on-whales#328]
Hi,

Is there a way for the `docker.execute()` to take a file of `psql` statements and function definitions instead of writing them out explicitly?

**Comment by gabrieldemarmiesse** [comment]
you can use a volume, or copy the file in the container before starting with 
`docker.copy("./myfile.sql", ("container_name", "/myfile.sql"))`

Then when you do `docker.execute()` just execute the file.

**Comment by Marston** [comment]
Thanks :-)
