### ISSUE TITLE
'Network Disconnect' calls cli command 'network disconnet'; fails on call

### ISSUE THREAD

**Issue by celoranta** [gabrieldemarmiesse/python-on-whales#330]
As referenced in the subject line, the CLI command called by the 'docker network disconnect' command in python is shown in the traceback as failing due to the CLI command 'docker network disconnet'

**Comment by gabrieldemarmiesse** [comment]
Thanks for the report! I'll take a look.

**Comment by gabrieldemarmiesse** [comment]
I made a pull request to fix this. You can expect the update to be available with pip install --upgrade today :)
