### ISSUE TITLE
Support for podman-remote?

### ISSUE THREAD

**Issue by LewisGaul** [gabrieldemarmiesse/python-on-whales#349]
(It seems reasonable that this might be closed as "won't fix" since it's simply a case where podman is not a drop-in replacement for the docker CLI... Partly opening to help others who might encounter this issue.)

It's great that this package supports other CLI executables via e.g. `python_on_whales.DockerClient(client_call=["podman"])`, where the assumption is that the supplied exe is fully compatible with the docker CLI (at least for the functionality that's used).

I tried to use this with podman-remote v3.4.4, i.e. `DockerClient(client_call=["podman-remote"], host="ssh://root@localhost:58011/run/podman/podman.sock")`, however commands then fail with:
```
>>> client.images()
DockerException: The docker command executed was `podman-remote --host ssh://root@localhost:58011/run/podman/podman.sock image list --quiet --no-trunc`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'Error: unknown flag: --host'
```

Basically the mechanism for connecting to podman using `podman-remote` is slightly different to docker, and the fact that some of the args are different means there's no way to get the above working currently.

Relevant differences:
- The podman-remote arg is called `--url` instead of `--host`, and expects the `/run/podman/podman.sock` path on the end (for SSH connections - I'm not sure why...)
- The `--identity` arg must be passed for SSH connections too (path to an SSH key to use), again I'd consider this a bug in podman-remote that it can't use the system SSH keys by default (I think they're aware of this issue)

There is a workaround however: use `CONTAINER_HOST` and `CONTAINER_SSHKEY` env vars and don't specify a 'host' when creating the `python_on_whales.DockerClient`. Example:
```python
import os
import python_on_whales as whales

os.environ["CONTAINER_HOST"] = "ssh://root@my-vm-host/run/podman/podman.sock"
os.environ["CONTAINER_SSHKEY"] = os.path.expanduser("~/.ssh/id_rsa")
client = whales.DockerClient(client_call=["podman-remote"])
client.images()
```

**Comment by gabrieldemarmiesse** [comment]
There is already a solution to this problem :)
Client call is a list, you can provide the binary as well as arbitrary arguments that are necessary for it to work

It shoud solve your issue. I think the documentation has some examples

**Comment by gabrieldemarmiesse** [comment]
For future readers

https://gabrieldemarmiesse.github.io/python-on-whales/docker_client/#dockerclient

```python
from python_on_whales import DockerClient

podman = DockerClient(
    client_call=[
        "podman-remote", "--url", "ssh://root@localhost:58011/run/podman/podman.sock", 
        "--identity", "/home/my_user/.ssh/id_rsa"
    ]
)
podman.run("hello-world")
```

**Comment by gabrieldemarmiesse** [comment]
@LewisGaul can I close this issue?

**Comment by gabrieldemarmiesse** [comment]
You are right. We don't want to have code that handles other clients specifically, because we would oupen ourselves to a lot of maintenance work. But on the other hand, modifying the documentation to explain some pitfalls is completely fine by me.

If you want to modify the docs and add some exemples for podman, feel free to. If we notice that a significant amount of the doc is relative to podman, we can have a dedicated user guide in the user guide section. Something like "how to call Podman".

**Comment by gabrieldemarmiesse** [comment]
A bit of doc was added for the support of podman. I think we can close this issue :)
