### ISSUE TITLE
docker compose ls -> docker.compose.ls()?

### ISSUE THREAD

**Issue by marshall7m** [gabrieldemarmiesse/python-on-whales#367]
AFAIK there isn't a method to handle `docker compose ls` CLI command. Just wondering if there's anything in the works to add support for this.

**Comment by gabrieldemarmiesse** [comment]
At first I thought that it was equivalent to `docker.ps()` but it seems that it filters per compose project. Thus it makes sense to implement it. I'll do it when I have time. If you wish you can open a pull request too :)

**Comment by marshall7m** [comment]
@gabrieldemarmiesse thanks for the response. I can get a PR going sometime this week

**Comment by gabrieldemarmiesse** [comment]
That would be awesome, thanks!
