### ISSUE TITLE
Feature Request - option to run container rather than pull and run

### ISSUE THREAD

**Issue by bthoughton** [gabrieldemarmiesse/python-on-whales#369]
Hello,

We are trying to utilize `python_on_whales` in a slightly unusual situation. We created a CLI which implements a subset of Docker commands to execute containers in the Kubernetes, instead of locally. A certain number of docker commands from the CLI of the cluster will (from the perspective of the user) appear to act just like they normally do. Since `python_on_whales` seems to primarily interface with docker through the CLI it is a great fit for us. 

However, we are running into issues when calling `python_on_whales.docker.run()` method, as it calls `docker image inspect` and `docker image pull`. Kubernetes API does not have image management, as a result we cannot implement any of the `docker image ...` commands. 

Ideally, `python_on_whales` would have an optional argument which rather than issuing `docker image` commands would simply perform a `docker run` command, which should work for us and also work in a local Docker environment as well.

Thank you for your time and consideration!

Cheers,

Ben

**Comment by gabrieldemarmiesse** [comment]
Hello, I think in recent version of Docker, there is an argument to docker run that would allow us to do that.

```
    --pull string                    Pull image before running ("always"|"missing"|"never") (default "missing")
```

In your case, if we use "never" then python-on-whales should not try to inspect and pull the docker image. We should implement this feature :)

**Comment by bthoughton** [comment]
That would be great if this was implemented!

**Comment by gabrieldemarmiesse** [comment]
No worries, with the implementation of @MisterOwlPT it should work out and never call `docker image ...` if you specify `pull="never"`.

**Comment by gabrieldemarmiesse** [comment]
Fixed with the new flag `pull="never"` :)
