### ISSUE TITLE
problem with python3.6 use

### ISSUE THREAD

**Issue by zero-pytagoras** [gabrieldemarmiesse/python-on-whales#387]
Hello,
I'm usingp ython3.6 on bastion host with some permissions and getting error with `__future__`  package not having `annotations`
error is below.
```py
from python_on_whales import docker
  File "/home/sddc-user/.local/lib/python3.6/site-packages/python_on_whales/components/buildx.py", line 1
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined
```
is there some dependencies needed ? can i define annotations manually ?

**Comment by gabrieldemarmiesse** [comment]
Hi! Python-on-whales only works with python 3.7 and above :)

**Comment by zero-pytagoras** [comment]
yes - I 've realize that: i'd suggest to make it part of dependencies

**Comment by gabrieldemarmiesse** [comment]
The end of life for python 3.6 was one year ago. We can't try to adapt the codebase for all dead versions of python

**Comment by zero-pytagoras** [comment]
You are correct, yet many places are still stuck with older versions, thus there always will be someone for whom the project will not work. So for you to have less work and not support those older version, make py3.7 to be part of requirement/dependency.

**Comment by gabrieldemarmiesse** [comment]
It's weird because it's already declared there: https://github.com/gabrieldemarmiesse/python-on-whales/blob/dcf2e6e5cbe048d0466932d4f0b1f079428c8207/setup.py#L22

Maybe the declaration is not working?

**Comment by zero-pytagoras** [comment]
probably, because i was able to install the package but can not import the object in python shell

**Comment by LewisGaul** [comment]
@zero-pytagoras Could you check the version of `python-on-whales` you have installed, with e.g. `python3 -m pip freeze | grep whales`? My guess is pip is resolving to an older version that does not have the restriction (but perhaps still doesn't work with python 3.6).
