### ISSUE TITLE
advanced docker.run() command

### ISSUE THREAD

**Issue by reemTamimi** [gabrieldemarmiesse/python-on-whales#391]
Hello, I would like to convert a docker degauss command that I currently use in the command line in docker. The current command that I use in the command line is:

docker run --rm -v $PWD:/tmp degauss/geocoder:3.0.1 my_address_file.csv 

I would like to convert this command to a python statement that I can include in my python script.

Please let me know if you need more information from me :)

**Comment by gabrieldemarmiesse** [comment]
Hi!
I think something like this could work
```python
from python_on_whales import docker
from pathlib import Path

docker.run("degauss/geocoder:3.0.1", "my_address_file.csv", remove=True, volumes=[(Path(".").absolute(), "/tmp")])
```

**Comment by reemTamimi** [comment]
Thank you very much for the helpful response! When I run this, it is able to identify the degauss command, but it seems it cannot identify the input file. When the input file is parsed, it is adding spaces in between each letter. I receive this error:

Error in argparser::parse_args(p) : 
  Extra arguments supplied: expecting 1 values but got 19 values: (m, y, _, a, d, d, r, e, s, s, _, f, i, l, e, ., c, s, v).
Execution halted

and this exception:

python_on_whales.exceptions.DockerException: The docker command executed was `/usr/local/bin/docker container run --rm --volume /Users/reem.tamimi/Desktop:/tmp degauss/geocoder:3.0.1 m y _ a d d r e s s _ f i l e . c s v`.

Let me know if I can provide more detail :)

**Comment by reemTamimi** [comment]
That worked! Thank you very much :)
