### ISSUE TITLE
`docker.system.prune` doesn't output anything

### ISSUE THREAD

**Issue by IrwenXYZ** [gabrieldemarmiesse/python-on-whales#396]
the command works but there's no output shown to indicate what was cleared.

the following is the command I used in my script
`docker.system.prune(all=True, volumes=True)`

**Comment by gabrieldemarmiesse** [comment]
Currently, we don't return anything with this function. One cool feature would be to parse the output and return what was removed. I'm open to contributions :)

**Comment by IrwenXYZ** [comment]
Would love to contribute but I honestly have no clue where to begin with what little experience I have with Python.

What I've gathered is that the code for the actual prune command is here but I'm not sure where the output goes.

https://github.com/gabrieldemarmiesse/python-on-whales/blob/bc9a3cb399ed377b45ad4082aa00a95e5bdbc3de/python_on_whales/components/system/cli_wrapper.py#L156-L172

**Comment by anesmemisevic** [comment]
is this one still relevant or putting `tty=True` in `run` is enough?

**Comment by anesmemisevic** [comment]
> is this one still relevant or putting `tty=True` in `run` is enough?

or would simply `stream_logs=True` help with this? provided that we add stream_logs functionality for prune commands?

**Comment by gabrieldemarmiesse** [comment]
I believe an option to stream the logs could indeed be a nice feature. Pruning ca' take a long time, so it makes sense to be able to grab the output as it's produced
