### ISSUE TITLE
Failing to get container ID from legacy build output with podman

### ISSUE THREAD

**Issue by LewisGaul** [gabrieldemarmiesse/python-on-whales#401]
Following https://github.com/gabrieldemarmiesse/python-on-whales/pull/346 and https://github.com/gabrieldemarmiesse/python-on-whales/pull/351, it turns out parsing the container ID from 'podman build' is still not quite right - when there's output on stderr from 'RUN' commands in the Dockerfile this is included in the output and interpreted as part of the container ID.

I think a fix could be as simple as:
```diff
- image_id = run(full_cmd).strip()
+ image_id = run(full_cmd).splitlines()[-1].strip()
```

I'd be happy to implement and test this fix at some point, when I have time.

Example Dockerfile that reproduces the issue with podman v3.4.2:
```
FROM alpine
RUN sh -c 'echo "hello" >&2'
```

**Comment by gabrieldemarmiesse** [comment]
A change like that would be fine by me. We have unit tests anyway that should cover this with Docker so I don't think we can break existing docker code
