### ISSUE TITLE
Default image output from buildx v0.10 cannot run on Google Cloud Run or AWS Lambda/ECS

### ISSUE THREAD

**Issue by darpham** [gabrieldemarmiesse/python-on-whales#407]
### Background
https://github.com/docker/buildx/issues/1533
https://github.com/docker/build-push-action/pull/781

As of Buildx 0.10, images are built with provenance -- this behavior is opt-out, and can be disabled with --provenance=false if using the buildx build cl

Images built with these default attestations that use the [attestation storage](https://github.com/moby/buildkit/blob/master/docs/attestations/attestation-storage.md) from buildkit cannot be run on Google Cloud Run or AWS Lambda. While both Cloud Run and Lambda support the OCI format, they do not support multi-platform images.

### Changes?
Add `provenance` arg for `BuildxCLI`
```
def build(
        self,
        ...
        provenance: ...,
    )...
...
        full_cmd.add_args_list("--provenance", format_dict_for_cli(provenance))
```

**Comment by gabrieldemarmiesse** [comment]
Hi! Thank you for the report! It seems like it is quite a big issue. As always, I'm open to pull requests to support new options added to Docker :) If nobody does the pull request, I'll do it when I have the time. If you decide to make the pull request, please make some minimal unit tests
