### ISSUE TITLE
docker.execute with output to terminal

### ISSUE THREAD

**Issue by Qaldak** [gabrieldemarmiesse/python-on-whales#418]
I would like to get some statistics from inside my running Docker container. For this, I need to execute a command inside the Docker container.

My idea is something like that:
```
stats = docker.execute("<container name>", "<command>", interactive=True, tty=True)
print(stats)
```

But I can't get it to work. 

I receive "_the input device is not a TTY_" if I run in pyCharm.
If I run in terminal, I got "_OCI runtime exec failed: exec failed: unable to start container process: exec: "<command>": executable file not found in $PATH: unknown_"

Is that even possible?

**Comment by gabrieldemarmiesse** [comment]
In this situation, I don't think you want to use interactive and TTY

**Comment by Qaldak** [comment]
Yes, that was also my thought. But then following error occurs:

_It returned with code 126
The content of stdout is 'OCI runtime exec failed: exec failed: unable to start container process: exec: "<command>": executable file not found in $PATH: unknown
'
The content of stderr is ''_

**Comment by gabrieldemarmiesse** [comment]
I think the command shoud be a list

**Comment by Qaldak** [comment]
You're right. It works with a list:
`stats = docker.execute("<container name>", ["<command>"])`

example: `metrics = (docker.execute("busybox", ["sh", "-c", "whoami ; pwd"]))`
