### ISSUE TITLE
Use another library to generate our documentation

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [gabrieldemarmiesse/python-on-whales#434]
We currently use keras-autodoc https://github.com/keras-team/keras-autodoc to generate the markdown for our documentation. We then use mkdocs to convert that to html.

Keras-autodoc isn't supported anymore, we need a remplacement before the CI starts breaking (shouldn't be urgent but we need to do it at some point). We should look into a replacement like https://github.com/NiklasRosenstein/pydoc-markdown or similar https://github.com/mkdocstrings/mkdocstrings

It doesn't matter if the documentation is different afterwards

**Comment by kclamalex** [comment]
Hey I could take a look at it! Will prepare the PR for this.

**Comment by gabrieldemarmiesse** [comment]
That would be great, thanks! Don't hesitate to ask if you need help or guidance!

**Comment by gabrieldemarmiesse** [comment]
It looks really good! Thanks @kclamalex !
