### ISSUE TITLE
No support for buildx build --build-context ...

### ISSUE THREAD

**Issue by bigcat2014** [gabrieldemarmiesse/python-on-whales#439]
## Background
https://github.com/docker/buildx/releases/tag/v0.8.0

Build command now accepts --build-context flag to define additional named build contextes for your builds. For example, these can be used expose additional local directories to your build or pin an image to a specific digest. This feature requires using Dockerfile 1.4+ frontend. https://github.com/docker/buildx/pull/904 [Documentation](https://github.com/docker/buildx/blob/v0.8.0/docs/reference/buildx_build.md#build-context)

## Changes
Add --build-context arg for BuildxCLI

```
def build(
        self,
        ...
        build_contexts: Dict[str, str] = {},
    )...
...
full_cmd.add_args_list("--build-context", format_dict_for_cli(build_contexts))
```

**Comment by gabrieldemarmiesse** [comment]
Thanks for creating the issue. This is a cool feature and a welcomed one. If anyone wants to make a pull request, I'll gladly review it :)
