### ISSUE TITLE
Password is shown in exception

### ISSUE THREAD

**Issue by zimmdi** [gabrieldemarmiesse/python-on-whales#456]
Using this library to run a project we found out, that the password is shown in the "command_launched".
This can allow other users to see the password (and username) and use it.

**Comment by gabrieldemarmiesse** [comment]
Hi, thanks for the issue! Can you explain a bit why you are using a password? Is it for sudo access? Docker login? Is it the password of a database?

**Comment by zimmdi** [comment]
Yes, sure.
we are doing a normal docker pull and docker push using this library
docker_client.login(
            username=username,
            password=password,
            server=docker_image,
        )
and follow up with a
docker_client.pull(docker_image)

If it cannot log in, it will show the password in the Exception

example code
```
import logging
from python_on_whales import DockerClient
from python_on_whales.utils import DockerException

docker_client = DockerClient()

docker_image = 'somethingstupid'
try:
    docker_client.login(username='Dirk.Zimmermann', password='THISSHOULDNOTBEVISIBLE', server=docker_image)
except DockerException as e:
    logging.warning("Docker Exception %s", e)
```

**Comment by gabrieldemarmiesse** [comment]
Thank you. Indeed this should be considered as a bug and fixed. We should pass some kind of blacklist of strings to remove from any debug/error message, and the password should go in there. then we could do something like
```python
for item in blacklist:
    error_message = error_message.replace(item, "xxxxxxxxxxx")
```
I'm open to a pull request if you're motivated, otherwise I'll make the PR myself, but there is no garantee on the timeline

**Comment by zimmdi** [comment]
It is in the process list as well (the password in cleartext) This is not known for me how this can be fixed. But for the exception i can try.

**Comment by zimmdi** [comment]
First try, check if you like it.
https://github.com/gabrieldemarmiesse/python-on-whales/pull/457

**Comment by gabrieldemarmiesse** [comment]
Awesome! I'll take a look!

**Comment by gabrieldemarmiesse** [comment]
Now that you mention it, I indeed didn't think about it showing in the process list. In which case that doesn't work to use a blacklist. Maybe we should move toward a more conventional approach? Most client recomment passing password with stdin and I think it should be fairly easy to do it with python-on-whales. Some other command already interact with stdin. What do you think of this solution @zimmdi ?

**Comment by gabrieldemarmiesse** [comment]
can you try out the new master branch?

**Comment by zimmdi** [comment]
Hi,
tried in master branch. Here a compare before/after
Before:
`python_on_whales.exceptions.DockerException: The docker command executed was '/Users/myusername/Library/Application Support/multipass/bin/docker login --username MyUser --password MyPassword l-docker-test.artifactory.athome.net'.
`
After:
`python_on_whales.exceptions.DockerException: The docker command executed was '/Users/myusername/Library/Application Support/multipass/bin/docker login --password-stdin --username MyUser l-docker-test.artifactory.athome.net'.`

So fine with me

**Comment by gabrieldemarmiesse** [comment]
good! I'll try to make a release tomorrow :)
