### ISSUE TITLE
Pydantic spurious output since v0.64.0

### ISSUE THREAD

**Issue by dboreham** [gabrieldemarmiesse/python-on-whales#461]
Since updating to v0.64.0 I'm seeing this output:

```
venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
```

Reverting to pydantic 1 is a workaround.

**Comment by gabrieldemarmiesse** [comment]
Thanks for the information! That should be an easy fix!

**Comment by shalevm** [comment]
any news on fixing this issue? (i've reverted to 1.10.12 for now which indeed works)
thanks.

**Comment by gabrieldemarmiesse** [comment]
This should be fixed with 0.64.1 :)

**Comment by gabrieldemarmiesse** [comment]
I think we can close this issue?

**Comment by dboreham** [comment]
I think so.
