### ISSUE TITLE
Question: Does remove(container) block the calling (python) thread?

### ISSUE THREAD

**Issue by jamespilcher** [gabrieldemarmiesse/python-on-whales#468]
When removing a container with docker_client.container.remove(container), will my python script **wait** for this container to be fully removed before proceeding, or do I need to poll to ensure the container has been removed?

Essentially: Does the .remove() block the calling thread?

**Comment by gabrieldemarmiesse** [comment]
You don't need to poll, subprocess are not detached, so when the function returns, you are garanteed that the container doesn't exist anymore.

Disclaimer: If docker recently changed the behavior of the remove command I might not know about it.
