### ISSUE TITLE
Container inspection fails with podman

### ISSUE THREAD

**Issue by ambasta** [gabrieldemarmiesse/python-on-whales#472]
In `components.container.models.ContainerConfig`, `stop_signal` only accepts strings. Podman otoh, responds with `StopSignal: 15`, i.e. integer values.

The line

https://github.com/gabrieldemarmiesse/python-on-whales/blob/d8851391069357b853c683b002b7bde7c4cd0234/python_on_whales/components/container/models.py#L218

should probably be `stop_signal: Optional[str | int] = None`

**Comment by gabrieldemarmiesse** [comment]
Thanks for the report! I'm open to a pull request with the fix and a unit test (we have some dummy json files that we try to load into the model, we just need to add one example there). If no one does the PR, I'll make it myself but I don't guarantee it's going to be quick.

**Comment by ambasta** [comment]
Sure, fired a PR. Is there a way I can test the PR locally before pushing again (without having docker installed)

**Comment by gabrieldemarmiesse** [comment]
Sadly we only support docker for unit testing but I would like some day to support podman and nerdctl too.

I'll take a look at the PR, thanks!
