### ISSUE TITLE
Support for compse up --renew-anon-volumes

### ISSUE THREAD

**Issue by avgdev** [gabrieldemarmiesse/python-on-whales#475]
Hello, thanks for the great module. Will it be possible to add support for the `--renew-anon-volumes` parameter to `docker compose up`. See [up options docs](https://docs.docker.com/engine/reference/commandline/compose_up/#options)

**Comment by gabrieldemarmiesse** [comment]
Sure thing! I'm open to pull requests too if you have the time :) otherwise, I'll implement it when I can

**Comment by avgdev** [comment]
Sure, will submit one shortly. Thanks!

**Comment by gabrieldemarmiesse** [comment]
Fixed by #487
