### ISSUE TITLE
Meta: Consider enabling discussions?

### ISSUE THREAD

**Issue by LewisGaul** [gabrieldemarmiesse/python-on-whales#481]
Hey @gabrieldemarmiesse, what do you think about enabling discussions on the repo? Might be a better place for meta questions like this and also for things like show-and-tell or general questions?

I have a show-and-tell to share - some tests exercising systemd in containers using python-on-whales: https://github.com/LewisGaul/systemd-containers

**Comment by gabrieldemarmiesse** [comment]
Sure thing, I didn't think they had to be enabled manually, let me change that

**Comment by gabrieldemarmiesse** [comment]
Done!
