### ISSUE TITLE
Add `platform` param to `buildx.create()`

### ISSUE THREAD

**Issue by rcwbr** [gabrieldemarmiesse/python-on-whales#540]
When using the [`buildx.create` function](https://gabrieldemarmiesse.github.io/python-on-whales/sub-commands/buildx/#python_on_whales.components.buildx.cli_wrapper.BuildxCLI.create), it should be possible to specify the platform of the builder container as with the [`docker buildx create --platform` flag](https://docs.docker.com/engine/reference/commandline/buildx_create/#options). This could look something like
```python
buildx.create(
    name="builder-name",
    driver="docker-container",
    platforms=["linux/amd64"],
    use=True,
)
```

**Comment by gabrieldemarmiesse** [comment]
Sure thing. I'm open to such a pull request.
