### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by elafontaine** [gabrieldemarmiesse/python-on-whales#555]
Sorry if I'm generating noise, but I believe this line was supposed to say "Task" and not "Image" ; https://github.com/gabrieldemarmiesse/python-on-whales/blob/4ed016dcc8fa566a5bb1429c5cc5c73cd2864bc6/python_on_whales/components/task/cli_wrapper.py#L93

**Comment by gabrieldemarmiesse** [comment]
Oupsy, you're totally right. This is a bug. PR welcome!
