### ISSUE TITLE
docker.compose.build is failing when passing a str variable in services 

### ISSUE THREAD

**Issue by abhisheksingh94** [gabrieldemarmiesse/python-on-whales#560]
This is what I'm passing

svc_list='stock'

docker.compose.build(services= svc_list , cache=False, progress=None, pull=True, quiet=False, ssh=None, stream_logs=True)

but it gives out error because instead of it doing 
docker compose --file ./docker-compose.yml build --no-cache --pull stock
it does
docker compose --file ./docker-compose.yml build --no-cache --pull s t o c k

surprisingly  docker.compose.stop(services=svc_list) works fine.

**Comment by gabrieldemarmiesse** [comment]
It should be a list of strings, but I don't see why we can't accept just a string too. I'll see if it's possible to change this to convert automatically to a list when a string is passed. You should use a list as a fix in the meantime.
