### ISSUE TITLE
Cache-installed docker doesn't include the compose plugin

### ISSUE THREAD

**Issue by faec** [gabrieldemarmiesse/python-on-whales#575]
Using python-on-whales to orchestrate CI machines, some commands produce the following failure:

```
failed on setup with "python_on_whales.exceptions.DockerException: The docker command executed was `/root/.cache/python-on-whales/docker-cli/20.10.5/docker compose [...]`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'unknown flag: --file
```

Further inspection of the error output shows that docker doesn't recognize `compose` as a valid command. This seems to be because python-on-whales installed the base docker engine but not the compose plugin. Manually adding the plugin as in [this documentation](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually) seems to fix the issue. This is only an issue on systems that don't already have docker (with compose) installed.

I'm preparing a PR to fix this case, but any extra context or advice would be welcome.

**Comment by LewisGaul** [comment]
Hi @faec, one relevant point is that the plan is to remove the functionality of python-on-whales where it downloads the docker client, see https://github.com/gabrieldemarmiesse/python-on-whales/issues/512#issuecomment-1872322431.

**Comment by faec** [comment]
@LewisGaul Ah, thank you! In that case maybe I'll work on fixing this in our CI initialization scripts instead
