### ISSUE TITLE
docker.network.list documentation missing

### ISSUE THREAD

**Issue by stock90975** [gabrieldemarmiesse/python-on-whales#623]
Firstly, great module!!! Starred!!!

docker.network.list()  works, but

I think that documentation is missing from:
https://gabrieldemarmiesse.github.io/python-on-whales/sub-commands/network/

Unless it's somewhere else ...

**Comment by gabrieldemarmiesse** [comment]
Thank you for the report. Indeed you are right, it's missing. I can see also that `docker.network.inspect()` and `docker.network.prune()` are not in the docs. Looking at the code, it's the only functions where a docstring is missing.

I believe if we add a docstring, they should appear in the docs. A pull request is welcome!

**Comment by stock90975** [comment]
Just FYI I'm really (seriousy) a noob, but I will give it a shot!

**Comment by stock90975** [comment]
This may be due to my noobness, but just FYI I had a couple of errors when trying to
`python autogen.py && mkdocs serve`

1. No such file or directory `venv/python-on-whales/lib/python3.12/site-packages/img/full.png` (fixed by copying it there)
2. No such file or directory `venv/python-on-whales/lib/python3.12/site-packages/img/docker_clients.png` (fixed by copying it there)
3. Need to `sudo apt install podman` (installed)
4. Error: `python-on-whales/docs/generated_sources isn't an existing directory` (just mkdir)
5. Lots of `Warning:  reference to 'docker_client.md' is included in the 'nav' configuration, which is not found in the documentation files.` type of warnings
6. ... which probably explains 404s in all the pages
7. Also: Run tests / Render docs (pull_request) failed

So that's my excuse for not verifying that the added docstrings *actually* show up in the docs.
(+ my dog ate my code)

**Comment by gabrieldemarmiesse** [comment]
No worries, our current workflow to serve the docs locally isn't great at all. This is not very beginner friendly. I'll serve the docs from your pull request locally, with a bit of luck, everything should run fine and we'll be able to merge your pull request :)

**Comment by gabrieldemarmiesse** [comment]
Closing this issue as fixed :)
