### ISSUE TITLE
More baseline CI issues

### ISSUE THREAD

**Issue by LewisGaul** [gabrieldemarmiesse/python-on-whales#644]
Tests failing in https://github.com/gabrieldemarmiesse/python-on-whales/pull/641, https://github.com/gabrieldemarmiesse/python-on-whales/pull/642, https://github.com/gabrieldemarmiesse/python-on-whales/pull/643

These all look like issues related to breaking docker/podman changes...

- buildx tests:
```
FAILED tests/python_on_whales/components/buildx/imagetools/test_imagetools_cli_wrapper.py::test_imagetools_inspect_single_image - python_on_whales.exceptions.DockerException: The command executed was `/usr/bin/docker buildx imagetools inspect --raw python@sha256:b48b88687b1376f3135a048c8cdaccad4e8dd1af2f345c693a39b75a5683a3eb`.
It returned with code 1
The content of stdout is ''
The content of stderr is 'ERROR: docker.io/library/python@sha256:b48b88687b1376f3135a048c8cdaccad4e8dd1af2f345c693a39b75a5683a3eb: not found
'
```
- container tests:
```
FAILED tests/python_on_whales/components/test_container.py::test_init_container - AssertionError: assert 'configured' == 'created'
  - created
  + configured
FAILED tests/python_on_whales/components/test_container.py::test_update_nosuchcontainer[podman] - python_on_whales.exceptions.DockerException: The command executed was `/usr/bin/podman container update --cpus 1 grueighuri`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'Error: unknown flag: --cpus
'
```
- network tests (also affects `tests/python_on_whales/components/test_system.py::test_prune_prunes_network[podman]`):
```
FAILED tests/python_on_whales/components/test_network.py::test_network_create_remove[podman] - python_on_whales.exceptions.NoSuchNetwork: The command executed was `/usr/bin/podman network remove /home/runner/.config/cni/net.d/meiwnystd345jrawbjz3.conflist`.
It returned with code 1
The content of stdout is ''
The content of stderr is 'time="2024-10-19T23:03:27Z" level=warning msg="Error validating CNI config file /home/runner/.config/cni/net.d/meiwnystd345jrawbjz3.conflist: [plugin bridge does not support config version \"1.0.0\" plugin portmap does not support config version \"1.0.0\" plugin firewall does not support config version \"1.0.0\" plugin tuning does not support config version \"1.0.0\"]"
Error: unable to find network configuration for /home/runner/.config/cni/net.d/meiwnystd345jrawbjz3.conflist: network not found
'
```
- pod tests:
```
FAILED tests/python_on_whales/components/test_pod.py::test_create_devices_arg - python_on_whales.exceptions.DockerException: The command executed was `/usr/bin/podman pod create --name 0r4eud0rsfw4gk17ru0r --device /dev/net/tun`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'Error: unknown flag: --device
'
FAILED tests/python_on_whales/components/test_pod.py::test_create_exit_policy_arg - python_on_whales.exceptions.DockerException: The command executed was `/usr/bin/podman pod create --name qlbct9h5k9imn7icmgyd --exit-policy stop`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'Error: unknown flag: --exit-policy
'
FAILED tests/python_on_whales/components/test_pod.py::test_create_shm_size_arg - python_on_whales.exceptions.DockerException: The command executed was `/usr/bin/podman pod create --name tigrlj6cvbiz9uq0eqzm --shm-size 1024000`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'Error: unknown flag: --shm-size
'
```
- volume tests:
```
FAILED tests/python_on_whales/components/test_volume.py::test_volume_drivers[podman] - python_on_whales.exceptions.DockerException: The command executed was `/usr/bin/podman volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=100m,uid=1000`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'Error: Volume options size and inodes not supported. Filesystem does not support Project Quota
'
```

**Comment by gabrieldemarmiesse** [comment]
@LewisGaul do you have an idea of what triggered this? Is it an upgrade of podman or an upgrade of the github actions VM? I guess that if it was only the github actions VM, we wouldn't get errors like "Error: unknown flag: --shm-size". So a podman upgrade removed/renamed some arguments, is that correct?

**Comment by LewisGaul** [comment]
* Last passing run: https://github.com/gabrieldemarmiesse/python-on-whales/actions/runs/11326251013/job/31494810543 (docker v26.1.3 with buildx v0.10.0, podman v4.9.3)
* First failing run (only buildx and network failures): https://github.com/gabrieldemarmiesse/python-on-whales/actions/runs/11369569350/job/31627318227 (docker v26.1.3 with buildx v0.10.0, podman v3.4.4)
* Latest failing run: https://github.com/gabrieldemarmiesse/python-on-whales/actions/runs/11421606211/job/31778564978 (docker v26.1.3 with buildx v0.10.0, podman v3.4.4)

So the obvious problem here is the CI setup has started getting an old version of podman for some reason. For some reason the first failing run only installed the old version of podman in *some* of the test matrix runs, hence some passing. I can look into fixing the podman install step.

The docker buildx failure seems completely unrelated - I'm not familiar with what that testcase is doing.

**Comment by LewisGaul** [comment]
From the passing run: `podman is already the newest version (4.9.3+ds1-1ubuntu0.1).` - looks like something changed in the GH actions VM such that it no longer comes with the recent podman version installed...

**Comment by LewisGaul** [comment]
Seems like with "ubuntu-latest" specified we suddenly started getting 22.04 rather than 24.04 sometimes... Should be fixed by specifying "ubuntu-24.04", we'll just want to update this when 26.04 comes along.

**Comment by LewisGaul** [comment]
@gabrieldemarmiesse any insight into the buildx issue?

**Comment by LewisGaul** [comment]
The buildx issue still remains
